# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmAdvertencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmAdvertencia(object):
    def setupUi(self, FrmAdvertencia):
        FrmAdvertencia.setObjectName("FrmAdvertencia")
        FrmAdvertencia.resize(372, 164)
        self.btnAceptar = QtWidgets.QPushButton(FrmAdvertencia)
        self.btnAceptar.setGeometry(QtCore.QRect(140, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnAceptar.setFont(font)
        self.btnAceptar.setObjectName("btnAceptar")
        self.lblAdvertencia = QtWidgets.QLabel(FrmAdvertencia)
        self.lblAdvertencia.setGeometry(QtCore.QRect(40, 50, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblAdvertencia.setFont(font)
        self.lblAdvertencia.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAdvertencia.setObjectName("lblAdvertencia")

        self.retranslateUi(FrmAdvertencia)
        QtCore.QMetaObject.connectSlotsByName(FrmAdvertencia)

    def retranslateUi(self, FrmAdvertencia):
        _translate = QtCore.QCoreApplication.translate
        FrmAdvertencia.setWindowTitle(_translate("FrmAdvertencia", "Advertencia"))
        self.btnAceptar.setText(_translate("FrmAdvertencia", "Accept"))
        self.lblAdvertencia.setText(_translate("FrmAdvertencia", "Warning"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmAdvertencia = QtWidgets.QDialog()
    ui = Ui_FrmAdvertencia()
    ui.setupUi(FrmAdvertencia)
    FrmAdvertencia.show()
    sys.exit(app.exec_())
