# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmDatosRecibidos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmDatosRecibidos(object):
    def setupUi(self, FrmDatosRecibidos):
        FrmDatosRecibidos.setObjectName("FrmDatosRecibidos")
        FrmDatosRecibidos.resize(463, 439)
        self.btnCerrar = QtWidgets.QPushButton(FrmDatosRecibidos)
        self.btnCerrar.setGeometry(QtCore.QRect(190, 390, 75, 23))
        self.btnCerrar.setObjectName("btnCerrar")
        self.label = QtWidgets.QLabel(FrmDatosRecibidos)
        self.label.setGeometry(QtCore.QRect(160, 20, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tbl_tableWidget_DatosRecibidos = QtWidgets.QTableWidget(FrmDatosRecibidos)
        self.tbl_tableWidget_DatosRecibidos.setGeometry(QtCore.QRect(20, 50, 421, 321))
        self.tbl_tableWidget_DatosRecibidos.setObjectName("tbl_tableWidget_DatosRecibidos")
        self.tbl_tableWidget_DatosRecibidos.setColumnCount(4)
        self.tbl_tableWidget_DatosRecibidos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tableWidget_DatosRecibidos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tableWidget_DatosRecibidos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tableWidget_DatosRecibidos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tableWidget_DatosRecibidos.setHorizontalHeaderItem(3, item)

        self.retranslateUi(FrmDatosRecibidos)
        QtCore.QMetaObject.connectSlotsByName(FrmDatosRecibidos)

    def retranslateUi(self, FrmDatosRecibidos):
        _translate = QtCore.QCoreApplication.translate
        FrmDatosRecibidos.setWindowTitle(_translate("FrmDatosRecibidos", "Datos Recibidos "))
        self.btnCerrar.setText(_translate("FrmDatosRecibidos", "Close"))
        self.label.setText(_translate("FrmDatosRecibidos", "Data Received "))
        item = self.tbl_tableWidget_DatosRecibidos.horizontalHeaderItem(0)
        item.setText(_translate("FrmDatosRecibidos", "ID_S"))
        item = self.tbl_tableWidget_DatosRecibidos.horizontalHeaderItem(1)
        item.setText(_translate("FrmDatosRecibidos", "NB"))
        item = self.tbl_tableWidget_DatosRecibidos.horizontalHeaderItem(2)
        item.setText(_translate("FrmDatosRecibidos", "NS"))
        item = self.tbl_tableWidget_DatosRecibidos.horizontalHeaderItem(3)
        item.setText(_translate("FrmDatosRecibidos", "ID_S_NS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmDatosRecibidos = QtWidgets.QDialog()
    ui = Ui_FrmDatosRecibidos()
    ui.setupUi(FrmDatosRecibidos)
    FrmDatosRecibidos.show()
    sys.exit(app.exec_())
