# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmDijkstra.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmDijkstra(object):
    def setupUi(self, FrmDijkstra):
        FrmDijkstra.setObjectName("FrmDijkstra")
        FrmDijkstra.resize(387, 449)
        self.tbl_tableWidgetTX = QtWidgets.QTableWidget(FrmDijkstra)
        self.tbl_tableWidgetTX.setGeometry(QtCore.QRect(30, 50, 321, 291))
        self.tbl_tableWidgetTX.setLineWidth(0)
        self.tbl_tableWidgetTX.setShowGrid(True)
        self.tbl_tableWidgetTX.setGridStyle(QtCore.Qt.SolidLine)
        self.tbl_tableWidgetTX.setRowCount(0)
        self.tbl_tableWidgetTX.setObjectName("tbl_tableWidgetTX")
        self.tbl_tableWidgetTX.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tableWidgetTX.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tableWidgetTX.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tableWidgetTX.setHorizontalHeaderItem(2, item)
        self.btnEnviarRutas = QtWidgets.QPushButton(FrmDijkstra)
        self.btnEnviarRutas.setGeometry(QtCore.QRect(30, 360, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnEnviarRutas.setFont(font)
        self.btnEnviarRutas.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.btnEnviarRutas.setObjectName("btnEnviarRutas")
        self.btnVerNodosyPesos = QtWidgets.QPushButton(FrmDijkstra)
        self.btnVerNodosyPesos.setGeometry(QtCore.QRect(130, 400, 111, 23))
        self.btnVerNodosyPesos.setObjectName("btnVerNodosyPesos")
        self.btnVerTodosDatosRecibidos = QtWidgets.QPushButton(FrmDijkstra)
        self.btnVerTodosDatosRecibidos.setGeometry(QtCore.QRect(250, 400, 101, 23))
        self.btnVerTodosDatosRecibidos.setObjectName("btnVerTodosDatosRecibidos")
        self.label = QtWidgets.QLabel(FrmDijkstra)
        self.label.setGeometry(QtCore.QRect(80, 10, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pgbrPogressBar = QtWidgets.QProgressBar(FrmDijkstra)
        self.pgbrPogressBar.setGeometry(QtCore.QRect(130, 360, 221, 31))
        self.pgbrPogressBar.setProperty("value", 0)
        self.pgbrPogressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.pgbrPogressBar.setOrientation(QtCore.Qt.Horizontal)
        self.pgbrPogressBar.setObjectName("pgbrPogressBar")

        self.retranslateUi(FrmDijkstra)
        QtCore.QMetaObject.connectSlotsByName(FrmDijkstra)

    def retranslateUi(self, FrmDijkstra):
        _translate = QtCore.QCoreApplication.translate
        FrmDijkstra.setWindowTitle(_translate("FrmDijkstra", "Rutas Dijkstra"))
        item = self.tbl_tableWidgetTX.horizontalHeaderItem(0)
        item.setText(_translate("FrmDijkstra", "ID_DF"))
        item = self.tbl_tableWidgetTX.horizontalHeaderItem(1)
        item.setText(_translate("FrmDijkstra", "ID_DEFAULT"))
        item = self.tbl_tableWidgetTX.horizontalHeaderItem(2)
        item.setText(_translate("FrmDijkstra", "ID_FRAME(dec)"))
        self.btnEnviarRutas.setText(_translate("FrmDijkstra", "Send New\n"
"Routes"))
        self.btnVerNodosyPesos.setText(_translate("FrmDijkstra", "Nodes and weights"))
        self.btnVerTodosDatosRecibidos.setText(_translate("FrmDijkstra", "View data received"))
        self.label.setText(_translate("FrmDijkstra", "Dijkstra Algorithm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmDijkstra = QtWidgets.QDialog()
    ui = Ui_FrmDijkstra()
    ui.setupUi(FrmDijkstra)
    FrmDijkstra.show()
    sys.exit(app.exec_())
