# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmKruskal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kru(object):
    def setupUi(self, kru):
        kru.setObjectName("kru")
        kru.resize(406, 444)
        self.tbl_tableWidgetTX = QtWidgets.QTableWidget(kru)
        self.tbl_tableWidgetTX.setGeometry(QtCore.QRect(40, 60, 321, 291))
        self.tbl_tableWidgetTX.setLineWidth(0)
        self.tbl_tableWidgetTX.setShowGrid(True)
        self.tbl_tableWidgetTX.setGridStyle(QtCore.Qt.SolidLine)
        self.tbl_tableWidgetTX.setRowCount(0)
        self.tbl_tableWidgetTX.setObjectName("tbl_tableWidgetTX")
        self.tbl_tableWidgetTX.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tableWidgetTX.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tableWidgetTX.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tableWidgetTX.setHorizontalHeaderItem(2, item)
        self.btnEnviarRutas = QtWidgets.QPushButton(kru)
        self.btnEnviarRutas.setGeometry(QtCore.QRect(40, 370, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnEnviarRutas.setFont(font)
        self.btnEnviarRutas.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.btnEnviarRutas.setObjectName("btnEnviarRutas")
        self.btnVerNodosyPesos = QtWidgets.QPushButton(kru)
        self.btnVerNodosyPesos.setGeometry(QtCore.QRect(140, 410, 111, 23))
        self.btnVerNodosyPesos.setObjectName("btnVerNodosyPesos")
        self.btnVerTodosDatosRecibidos = QtWidgets.QPushButton(kru)
        self.btnVerTodosDatosRecibidos.setGeometry(QtCore.QRect(260, 410, 101, 23))
        self.btnVerTodosDatosRecibidos.setObjectName("btnVerTodosDatosRecibidos")
        self.pgbrPogressBar = QtWidgets.QProgressBar(kru)
        self.pgbrPogressBar.setGeometry(QtCore.QRect(140, 370, 221, 31))
        self.pgbrPogressBar.setProperty("value", 0)
        self.pgbrPogressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.pgbrPogressBar.setOrientation(QtCore.Qt.Horizontal)
        self.pgbrPogressBar.setObjectName("pgbrPogressBar")
        self.label = QtWidgets.QLabel(kru)
        self.label.setGeometry(QtCore.QRect(90, 20, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(kru)
        QtCore.QMetaObject.connectSlotsByName(kru)

    def retranslateUi(self, kru):
        _translate = QtCore.QCoreApplication.translate
        kru.setWindowTitle(_translate("kru", "Rutas Kruskal"))
        item = self.tbl_tableWidgetTX.horizontalHeaderItem(0)
        item.setText(_translate("kru", "ID_DF"))
        item = self.tbl_tableWidgetTX.horizontalHeaderItem(1)
        item.setText(_translate("kru", "ID_DEFAULT"))
        item = self.tbl_tableWidgetTX.horizontalHeaderItem(2)
        item.setText(_translate("kru", "ID_FRAME(dec)"))
        self.btnEnviarRutas.setText(_translate("kru", "Send New\n"
"Routes"))
        self.btnVerNodosyPesos.setText(_translate("kru", "Nodes and weights"))
        self.btnVerTodosDatosRecibidos.setText(_translate("kru", "View data received"))
        self.label.setText(_translate("kru", "Kruskal  Algorithm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kru = QtWidgets.QDialog()
    ui = Ui_kru()
    ui.setupUi(kru)
    kru.show()
    sys.exit(app.exec_())
